config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    resources :projects
    resources :todo_tasks
    resources :users do
    end
    get 'user/login/:id', to: 'users#login'
    put 'projects/:id/assign', to: 'projects#assign'
    put 'users/:id/assign_task', to: 'users#assign_todo_task'
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :project_users, inverse_of: :project
  has_many :users, through: :project_users, inverse_of: :projects

  belongs_to :manager, class_name: "User", foreign_key: "manager_id"
  accepts_nested_attributes_for :project_users
  accepts_nested_attributes_for :users

  validates_presence_of :name
  validates_uniqueness_of :name

  scope :active, -> { includes(:project_users).where( project_users: { active: true } ) } 
end

app/models/project_user.rb
class ProjectUser < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_many :users, dependent: :destroy
end

app/models/todo_task.rb
class TodoTask < ActiveRecord::Base
  belongs_to :user
  validates :name, uniqueness: true, presence: true

  enum status: { created: 0, in_progres: 4, completed: 8 }
  validates :status, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :project_users, inverse_of: :user, dependent: :destroy
  has_many :projects, through: :project_users, inverse_of: :users, dependent: :destroy
  belongs_to :role
  has_many :todo_tasks, dependent: :destroy
  accepts_nested_attributes_for :projects
  accepts_nested_attributes_for :project_users

  validates :email, uniqueness: true, presence: true

end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  respond_to :json
  before_action :authenticate_user

  private

  def authenticate_user
    @user = User.where(email: request.headers['email']).last
    unless @user.present?
      render json: { status: 401, message: "Not Authorized" } and return
    end
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < Api::BaseController
  before_action :authorize_admin_action, only: [:create, :assign]

  def create
    manager = User.find_by(email: params[:manager_email])
    if (params[:name] && manager).present?
      params[:manager_id] = manager.id
      @project = Project.new(project_params)
      if @project.save!
        @project.project_users.create(user_id: @user.id, active: true)
        render json: { success: true, message: " Project #{@project.name} created successfully" }
      else
        render json: { success: false, message: "Project: #{@project.name} creation failed. Errors: #{@project.errors.full_messages.join(',')}" }
      end
    else
      render json: { sucess: false, message: "Enter project name and manager email" }
    end
  end

  def index
    @projects = Project.all.active
    render json: @projects
  end

  def assign
    project = Project.where(id: params[:id]).last
    user    = User.where(email: params[:email]).last
    if (user && project)
      project.users << user
      render json: { sucess: true, message: "Project #{project.name} is assigned to user #{params[:email]}" }
    else
      render json: { sucess: false, message: "Please enter valid email and project id" }
    end
  end

  private

    def project_params
      params.permit(:name, :manager_id)
    end

    def authorize_admin_action
      unless @user.role.name.downcase == 'admin'
        render json: { status: 403, message: "Not authorized" } and return
      end
    end
end

app/controllers/api/todo_tasks_controller.rb
class Api::TodoTasksController < Api::BaseController
  before_action :authorize_admin_action, only: [:create]

  def index
    todo_tasks = @user.todo_tasks
    render json: { sucess:true, tasks: todo_tasks }
  end

  def create
    if (params[:name] && params[:detail]).present?
      @todo_task = @user.todo_tasks.new(todo_tasks_params)
      if @todo_task.save
        render json: { success: true, todo_task: @todo_task }
      else
        render json: { success: false, message: "Project: #{@todo_task.name} creation failed. Errors: #{@todo_task.errors.full_messages.join(',')}" }
      end
    else
      render json: {success: false, message: "Enter valid name and detail params."}
    end
  end

  def update
    todo_task = @user.todo_tasks.where(id: params[:id]).last
    state = TodoTask.statuses[params[:status]]
    if (todo_task && state).present?
      todo_task.status = state
      if todo_task.save
        render json: { success: true, message: "Status changed to #{todo_task.status}!" }
      else
        render json: { success: false, message: "TodoTask: updation failed. Errors: #{todo_task.errors.full_messages.join(',')}" }
      end
    else
      render json: { success: false, message: "Enter a valid status or valid task id." }
    end
  end

  private 

  def todo_tasks_params
    {
      status: 0,
      name: params[:name],
      detail: params[:detail]
    }
  end

  def authorize_admin_action
    unless @user.role.name.downcase == 'admin'
      render json: { status: 403, message: "Not authorized" } and return
    end
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < Api::BaseController
  before_action :authorize_admin_action, only: [:assign_todo_task]
  
  def create
  end

  def index
    @users = User.all
    render json: @users
  end

  def assign_todo_task
    todo = TodoTask.where(name: params[:name]).last
    user    = User.where(id: params[:id]).last
    if (user && todo)
      user.todo_tasks << todo
      render json: { sucess: true, message: "TodoTask #{todo.name} is assigned to user #{params[:email]}" }
    else
      render json: { sucess: false, message: "Please enter valid task name." }
    end
  end

  private def authorize_admin_action
    unless @user.role.name.downcase == 'admin'
      render json: { status: 403, message: "Not authorized" } and return
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery unless: -> { request.format.json? }
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_users_helper.rb
module ProjectUsersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/todo_tasks_helper.rb
module TodoTasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectMg</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/project_users/_form.html.erb
<%= form_for(@project_user) do |f| %>
  <% if @project_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_user.errors.count, "error") %> prohibited this project_user from being saved:</h2>

      <ul>
      <% @project_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_users/edit.html.erb
<h1>Editing Project User</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_user %> |
<%= link_to 'Back', project_users_path %>

app/views/project_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Project Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_users.each do |project_user| %>
      <tr>
        <td><%= link_to 'Show', project_user %></td>
        <td><%= link_to 'Edit', edit_project_user_path(project_user) %></td>
        <td><%= link_to 'Destroy', project_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project user', new_project_user_path %>

app/views/project_users/new.html.erb
<h1>New Project User</h1>

<%= render 'form' %>

<%= link_to 'Back', project_users_path %>

app/views/project_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_project_user_path(@project_user) %> |
<%= link_to 'Back', project_users_path %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/todo_tasks/_form.html.erb
<%= form_for(@todo_task) do |f| %>
  <% if @todo_task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_task.errors.count, "error") %> prohibited this todo_task from being saved:</h2>

      <ul>
      <% @todo_task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_tasks/edit.html.erb
<h1>Editing Todo Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_task %> |
<%= link_to 'Back', todo_tasks_path %>

app/views/todo_tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Tasks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_tasks.each do |todo_task| %>
      <tr>
        <td><%= link_to 'Show', todo_task %></td>
        <td><%= link_to 'Edit', edit_todo_task_path(todo_task) %></td>
        <td><%= link_to 'Destroy', todo_task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo task', new_todo_task_path %>

app/views/todo_tasks/new.html.erb
<h1>New Todo Task</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_tasks_path %>

app/views/todo_tasks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_todo_task_path(@todo_task) %> |
<%= link_to 'Back', todo_tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>